### ISSUE TITLE
Nicer frontend

### ISSUE THREAD

**Issue by gmemstr** [gmemstr/pogo#1]
The current frontend is a bit hacked together, I want to avoid JS frameworks but if it's small enough I might consider it.

**Comment by hetenho** [comment]
I can refactor the frontend for this without a framework, using JS and CSS. I´ve been using React a lot, but maybe this does not need a framework.

**Comment by gmemstr** [comment]
@hetenho Sounds fantastic!

**Comment by gmemstr** [comment]
Heads up, currently rewriting the frontend in Vue.js - focusing on the admin interface, please see `vue-admin` branch for progress. Closing this issue until further notice.
