### ISSUE TITLE
Add proper encryption to users.json

### ISSUE THREAD

**Issue by gmemstr** [gmemstr/pogo#2]
Would like to add some sort of encryption to user login, I also plan to move this to a more modern cookie & POST login system soon but basic HTTP login works fine for the early stages. Would like to focus on getting encryption working because that's the more difficult part.

**Comment by ishanjain28** [comment]
@gmemstr I can add Encrypted cookies based sessions. 
It would work like this, 
1. When user logs in, A cookie encrypted with aes-256-cbc is created and sent with the request. 
2. A middleware can be put before every endpoint that requires authorization to access it. If the user is authorized, It'll pass the request to second endpoint and if the user is not authorized it'll send a 403 response.

Let me know if you would like to move straight to cookies based sessions and I'll start working on that.

**Comment by gmemstr** [comment]
@ishanjain28 Sounds good, would love to see what that would look like. 👍 Thanks!

**Comment by ishanjain28** [comment]
@gmemstr Before I start adding cookie sessions, Is it okay if I refactor it a bit. I would suggest create separate packages like `router`, `auth` and `common`.

Router will have code for all the endpoints, Auth will have the cookie sessions code and common will have code that is common to the two packages mentioned above and also `main` package

**Comment by gmemstr** [comment]
sounds good, I have no problem with this personally. all the better to learn go with!

**Comment by gmemstr** [comment]
#5 partly addresses this issue with encrypted cookie authentication vs. HTTP basic authentication, still have to encrypt user credentials, and will keep issue open.

**Comment by gmemstr** [comment]
Implemented bcrypt password checking, closing this issue. Still need to implement user management into admin dashboard but that isn't relevant to this issue.
