### ISSUE TITLE
Fully test Docker image

### ISSUE THREAD

**Issue by gmemstr** [gmemstr/pogo#6]
I currently natively develop in Windows 10 and don't want to go through the hassle of managing and testing Docker with each new build, I will be working on a script for TravisCI if possible but I want some help putting together some docs and fully testing the Dockerfile. Basically

- [x] Test to ensure the Dockerfile builds and properly runs Pogo
- [x] Write up steps to fetch Docker image and running it

I'm fairly new to Docker so this will be a learning experience for me as well 😋

**Comment by gabrielsclimaco** [comment]
Anything against using alpine version of golang base image?

**Comment by gabrielsclimaco** [comment]
I know a lot about Docker but I also don't know a thing about Go lang, so I'll need a little help in order to help you too.

Should I see the following warnings?
![image](https://user-images.githubusercontent.com/8144779/31311003-ab548760-ab79-11e7-8379-3cdcf114c7c0.png)

***P.S.*** : I am inside a Docker container trying to build pogo.

**Comment by gmemstr** [comment]
I am currently out but I'll fill in some more info ASAP, thanks!

**Comment by gmemstr** [comment]
Right so I'll tweak the Dockerfile right now to install godep properly and all that, please see and use `docker` branch for changes @gabrielsclimaco

**Comment by gmemstr** [comment]
Update: Have TravisCI hooked up and building the image, can someone better versed in TravisCI tell me why the build is marked as failed despite looking like it succeeded? [Build #47](https://travis-ci.org/gmemstr/pogo/builds/284817756)

**Comment by iblancasa** [comment]
Could this article help you to test your tool in a better way? https://medium.com/@aelsabbahy/tutorial-how-to-test-your-docker-image-in-half-a-second-bbd13e06a4a9

Regarding your question, I swat this on your build:
```bash
0.00s$ set -e
The command "set -e" exited with 0.
```

Could it be related to this? https://github.com/travis-ci/travis-ci/issues/891

**Comment by gmemstr** [comment]
@iblancasa I'll try just removing the `set -e` entry and see what happens, will go through the article and see what can be implemented. Thanks.

**Comment by iblancasa** [comment]
@gmemstr you are welcome :)

**Comment by gmemstr** [comment]
Docker (seems to be) working in TravisCI, closing this issue.

**Comment by circa10a** [comment]
`set -e` allows the build to fail if there are issues with building or running the image. If removed, your build has the ability to pass with a faulty docker image.

**Comment by gmemstr** [comment]
Fully updated and tested, working perfectly after #12. Updated in master branch & vue-admin branches.
