### ISSUE TITLE
Not include the dependencies in the repo

### ISSUE THREAD

**Issue by iblancasa** [gmemstr/pogo#9]
You are saving all the dependencies in the "vendor" folder, right?

This is not a good practice because it increases the size of the repository and makes more difficult to upgrade the dependencies to newer versions.

You have a Godeps file in your repository. You should use this instead host the dependencies at the repository.

**Comment by gmemstr** [comment]
I have been going back and forth on this, as the official Godep repository says 

> Read over the contents of vendor/ and make sure it looks reasonable. Then commit the Godeps/ and vendor/ directories to version control.

Yet I see a lot of people say you don't need to commit the vendor/ folder. I will remove it once I have the Docker/TravisCI issues ironed out (see docker branch and #6)

**Comment by iblancasa** [comment]
Oh! I did not know about this. Interesting.
Anyway, I think it is not a good practice. I will ask in the Godep repository.

**Comment by gmemstr** [comment]
Removed `vendor/` folder from repo and project seems to build fine, closing this issue.
